### ISSUE TITLE
Misspelling "concious" and variants are in the en_GB dictionary 

### ISSUE THREAD

**Issue by MHeasell** [marcoagpinto/aoo-mozilla-en-dict#12]
As in the title, the word "concious" and variants such as "conciousness" (etc.) are in the word list.

All the resources I could find via Google suggest that this is a misspelling and that the correct spelling is "conscious".

I think that this spelling and its variants should be removed from the list.

**Comment by marcoagpinto** [comment]
Well spotted!

I have removed both from en_GB.

Thank you very much!

Kind regards,
       >Marco A.G.Pinto
         ----------------------


On 26/01/2015 15:35, MHeasell wrote:
>
> As in the title, the word "concious" and variants such as 
> "conciousness" (etc.) are in the word list.
>
> All the resources I could find via Google suggest that this is a 
> misspelling and that the correct spelling is "conscious".
>
> I think that this spelling and its variants should be removed from the 
> list.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/marcoagpinto/aoo-mozilla-en-dict/issues/12>.
>


--
