### ISSUE TITLE
Please add "hyperlink"

### ISSUE THREAD

**Issue by yecril71pl** [marcoagpinto/aoo-mozilla-en-dict#13]
[hyperlink]  (http://www.oxforddictionaries.com/definition/english/hyperlink)

**Comment by marcoagpinto** [comment]
Hello!

The latest version of my en_GB is V2.22.

That word has been there since V2.05 - 24-SEP-2013 :


V2.05
-------
24-SEP-2013
306) hyperlink (+plural +ed)


Thanks!

Kind regards,
