### ISSUE TITLE
Add "website" to your list of words

### ISSUE THREAD

**Issue by vogella** [marcoagpinto/aoo-mozilla-en-dict#15]
I uses the seach for this repository and "website" did not show up as hit. Please add it, I think it is in common use.

**Comment by marcoagpinto** [comment]
Hello!

It was already in the wordlist:
website
website's
websites

Thanks,

Kind regards,
     >Marco A.G.Pinto
       ----------------------

**Comment by vogella** [comment]
What is the right way to search for this? Github search failed me. Should I clone your repo and grep for it?

**Comment by marcoagpinto** [comment]
Hi!

First check in the wordlist, which is a .txt file inside the folder:
en_GB (Marco Pinto) - 2.22 - 2015-03-01

If it not found there, then search in the file:
en_GB_speller_for_Mozilla+AOO+LO_2013+.txt

:p

Kind regards,
