### ISSUE TITLE
Missing words

### ISSUE THREAD

**Issue by okdana** [marcoagpinto/aoo-mozilla-en-dict#16]
Hello. I was actually about to fork this dictionary myself until i saw you'd
already done it, thanks.

Here are some entries i was going to add to my fork that i noticed yours seems
to lack.

Note that, where an affix is supplied, the word *itself* may be in your
dictionary — just not with the associated affix.

Also, regarding Americanisms: I understand that the original maintainers of this
dictionary deliberately chose to remove most of these. However, i feel like a
few of them are in common daily use in certain parts of the UK/Commonwealth, and
it doesn't hurt to have the rest in there for those occasions where it's useful
to use American terminology (for comparison, or speaking to Americans, or
whatever). The only one i consider potentially troublesome is *math*, since it's
more likely than the others to confuse a school child for example trying to find
the correct spelling of *maths* (the other ones you pretty much deliberately
have to be looking for).

PS: Sorry this isn't a pull request, i'm not sure i understand your update
methodology.

```
# Contractions
anything/M
can't've
couldn't've
everything/M
how'd
how're
how've
might've
mightn't've
nothing/M
s'pose
shouldn't've
there're
these'll
this'd
wouldn't've

# Curses
arse/GMS
arsehole/M
asshole/MS
half-arse/GS
half-ass/DG
horseshit/M
shit/M

# Medicine
anxiolytic/MS
clonazepam
hydrocodone
MAOI/S
naproxen
oxycodone
SSRI/S
sublingual/MSY

# Psychiatry
ADHD
BPD
CBT
cyclothymia
cyclothymic
DBT
dysmorphia
dysmorphic
dysphoria
dysphoric
dysthymia
dysthymic
MDD
NPD
schizoaffective
suicidality

# Programming/technology
backtick/MS
configurability
display/M
ECMAScript/M
lint/DG
microSD/M
pair/U
programmatically
symlink/DGMS
throbber/MS
tick/U
transclude/DGNS
wiki/M

# Internet culture
blog/M
blogger/M
grief/DG
griefer/MS

# Japanese language
hiragana
kana
kanji
katakana

# Discrimination
classism
classist/MS
heteronormative
heteronormativity
heterophobe/MS
heterophobia
heterophobic
heterosexism
homophobe/M
intersectional
intersectionality
intersectionalism
misandrist/MS
patriarchical
transphobe/MS
transphobia
transphobic

# Sexual/romantic orientation
aromantic
demisexual/MSY
demisexuality
heteroflexible

# Gender identity/expression
agender
androgyne/MS
androgynous/Y
bigender
cis
cisgender
genderfluid
genderqueer
trans

# Misc.
autotune/DGRS
cancellable
categorise/a
epilate/DGNS
epilator/SM
euthanise/DGS
isopropyl
sequitur/S
skort/S
trinary
unfulfilling
veganism

# Americanisms
deplane/DGS
enplane/DGS
infomercial/MS
math/M
movie/MS
salutatorian/MS
valedictorian/MS
windshield/MS
zipper/MS
zucchini/M
```

**Comment by danielnaber** [comment]
I'm not a native speaker, but Wiktionary lists `can't've`, `couldn't've` as "nonstandard". Also see http://english.stackexchange.com/questions/50/can-a-word-be-contracted-twice-e-g-ivent where most people seem to think these are not correct in written English.

**Comment by okdana** [comment]
> most people seem to think these are not correct in written English.

They're speaking of formal written English, where indeed they're considered inappropriate. But they are grammatically correct, and some double contractions (*shouldn't've* and *couldn't've* in particular) are common in native-level conversational English, especially in speech. A user from London on the page you linked mentions the phrase *you shouldn't've done that*, for instance, which is the same one that came to mind for me.

If Firefox's spell-checking implementation supported grammar checking i could see marking these words as incorrect (since grammar checkers almost universally apply formal rules), but all we're talking about here is spelling, and i'd say they are pretty much objectively spelt correctly.

Of course, at some point you have to define the scope of a dictionary. Not sure if this project has decided on one. But, for whatever it's worth, almost all of the words i've submitted here (minus some of the Americanisms) are ones i've personally found missing in the course of using Firefox as a native English speaker/writer.

**Comment by marcoagpinto** [comment]
Hello!

I will try to have a look at it tonight.

On the weekend I was the full day at my weekend job and didn't have time to read/reply to e-mails.

Right now I am about to check if I have work to do from my daily job at the university (done from home).

Thanks!

**Comment by marcoagpinto** [comment]
@okdana 

I have added around half of them so far, tomorrow I will continue.

This takes time because before adding I try to find them on on-line dictionaries and such, including Wikipedia.

There are some I haven't found anywhere, so I haven't added them.

Also, I am leaving out the ones which are Chiefly American.

@danielnaber is right, the contractions are non-standard, but I have added them.

Tomorrow I will continue the task but you can already see the text file in GitHub with my additions.

Thanks!

Kind regards,

**Comment by okdana** [comment]
I understand, thanks.

If it will help you to verify them, here are the meanings i had in mind for some
of the ones you haven't added yet:

```
DBT             — dialectical behavioural therapy (treatment for BPD, &al.)
MDD             — major depressive disorder (aka clinical depression)
schizoaffective — part of 'schizoaffective disorder')

lint            — code linting (related to static code analysis)
unpair          — opposite of pairing a device via Bluetooth or similar

autotune        — audio processing effect (genericised trademark)
epilate         — hair removal
epilator        — hair-removal device (like an electric shaver)
euthanise       — euthanasia (humane killing)
isopropyl       — aka isopropanol, aka surgical spirit, aka rubbing alcohol
sequitur        — part of 'non sequitur' (irrelevant/illogical statement)
skort(s)        — women's clothing
trinary         — aka ternary (meaning 'three')
veganism        — vegan dietary practice
```

The others that are left are all either Americanisms (already discussed) or
terms related to feminism, gender/queer studies, and/or social justice. Some of
those are too new/obscure to appear in OED, but i know many of them are on
Wikipedia and/or Wiktionary.

**Comment by marcoagpinto** [comment]
I have added the remaining non-American words.

The following words have hyphen in the Oxford dictionary:
- schizoaffective > schizo-affective (added two years ago)
7741) bi-gender
7742) bi-gendered

The word "euthanise" is American:
http://www.oxforddictionaries.com/definition/english/euthanize?q=euthanise

So, the words I have added are:
7-SEP-2015
7656) Europass (European Union site)
7657) anything's (added the 's)
7658) everything's (added the 's)
7659) how'd (Wiktionary)
7660) how're (Wiktionary)
7661) can't've (Wiktionary)
7662) couldn't've (Wiktionary)
7663) how've (Wiktionary)
7664) might've (Wiktionary)
7665) mightn't've (Wiktionary)
7666) nothing's (added the 's)
7667) shouldn't've (Wiktionary)
7668) there're (Wiktionary)
7669) this'd (Wiktionary)
7670) wouldn't've (Wiktionary)
7671) arses + arsing (merged into arse)
7672) half-arse (+ing +ed)
7673) anxiolytic (+plural)
7674) antiepileptics (added plural - Wiktionary)
7675) clonazepam
7676) hydrocodone (+plural - Wiktionary)
7677) MAOI
7678) naproxen
7679) oxycodone
7680) SSRI
7681) sublingual (+ally)
7682) ADHD (abbreviation: Attention deficit hyperactivity disorder)
7683) BPD
7684) CBT (abbreviation: Cognitive behavioural therapy)
7685) cyclothymia
7686) cyclothymic
7687) dysmorphia
7688) dysmorphic
7689) dysphoria
7690) dysphoric
7691) dysthymia
7692) dysthymic
7693) NPD
7694) suicidality
7695) backtick (+plural)
7696) configurability (Google)
7697) display's (added the 's)
7698) ECMAScript (+'s - Wiktionary)
7699) microSD (Wikipedia)
7700) programmatically
7701) symlink (+s +ing +ed)
7702) throbber (+plural)
7703) untick (+s +ing +ed - Wiktionary)
7704) transclude (+s +ing +ed - Wiktionary)
7705) wiki's (added the 's)
7706) blog's (added the 's)
7707) blogger's (added the 's)
7708) griefing + griefed (merged into grief - Wiktionary)
7709) griefer (+plural +'s)
7710) hiragana
7711) kana
7712) kanji
7713) katakana

8-SEP-2015
7714) classism
7715) classist (+plural)
7716) heteronormative
7717) heteronormativity
7718) heterophobe (+plural - Wiktionary)
7719) Hopkins's (added the 's - name - Wikipedia)
7720) heterophobia (Wiktionary)
7721) heterophobic (Wiktionary)
7722) heterosexism
7723) heterosexist
7724) intersectionality
7725) intersectional
7726) intersectionalism (Wiktionary)
7727) misandrist (+plural)
7728) patriarchically
7729) transphobe (+plural - Wiktionary)
7730) transphobia
7731) transphobic
7732) aromantic (+plural)
7733) aromanticism (Wiktionary)
7734) demisexual (+plural + ity - Wiktionary)
7735) demisexuality (Wiktionary)
7736) heteroflexible (Collins)
7737) agender
7738) teen's (added the 's - Wikipedia)
7739) androgyne (+plural)
7740) androgynously
7741) bi-gender
7742) bi-gendered
7743) cis
7744) substituent (+plural)
7745) methoxyl
7746) cisgender
7747) cisgendered
7748) gender-fluid
7749) genderqueer (+plural)
7750) trans
7751) autotune (+s +ing +ed +er +ers - merged into autotune)
7752) cancellable (Collins)
7753) miscategorise (+s +ing +ed - Wiktionary)
7754) epilation
7755) epilate (+s +ing +ed)
7756) epilator (+plural)
7757) isopropyl
7758) sequitur (+plural - non sequitur)
7759) trinary (Collins)
7760) unfulfillable
7761) unfulfilling
7762) veganism
7763) fruitarian (+plural)
7764) fruitarianism
7765) non-American
7766) unpair (+s +ing +ed - Wiktionary)
7767) linting (merged into lint - Collins)
7768) genericise (+s +ing +ed)

**Comment by okdana** [comment]
Thanks again.
