### ISSUE TITLE
word suggestions

### ISSUE THREAD

**Issue by lukeapage** [marcoagpinto/aoo-mozilla-en-dict#18]
Hi,

a few more technical word suggestions...

````
CLI - Command Line Interface
```

and possibly less common...

```
CI - Continuous Integration
```

```
minify - to make less, commonly used with javascript and css files.
minifying
minified
minifies
minification
transpile - https://en.wiktionary.org/wiki/transpile
transpiled
```

setup as opposed to set-up ?

**Comment by marcoagpinto** [comment]
Hello!

I have just added them:
8884) CLI (abbreviation: Command Line Interface)
8885) Ci (abbreviation: Curie)
8886) CI (abbreviation: several meanings)
8887) minify (+s +ing +ed +ion)
8888) transpile (+s +ing +ed +er +ers - Wiktionary)
8889) transcompile (+s +ing +ed - Wiktionary)
8890) setup (setup file - Collins)

The last one, "setup", appears as "set-up" in the Oxford dictionary. But I searched for it in Collins dictionary and there was the therm "setup file".

Thanks for the suggestions!

Kind regards,
     >Marco A.G.Pinto
       --------------------
