### ISSUE TITLE
New words

### ISSUE THREAD

**Issue by lukeapage** [marcoagpinto/aoo-mozilla-en-dict#20]
affordance
automobile
you have `ideate` but not `ideating`
repurpose, repurposing

**Comment by marcoagpinto** [comment]
Hello Luke,

The word "automobile" is an American word: http://www.oxforddictionaries.com/definition/english/automobile

So, based on your suggestions, I have added:
8953) affordance
8954) roofline (+plural) <- It was in the Oxford examples for "automobile"
8955) ideating + ideated (merged into ideate)
8956) repurpose (+s +ing +ed)
