### ISSUE TITLE
Idea: stop including dates in folder names to facilitate automation scripts

### ISSUE THREAD

**Issue by skkeeper** [marcoagpinto/aoo-mozilla-en-dict#22]
As stated in the title, if you could remove the dates from the folder names I think it would make writing scripts that automatically download up to date dictionaries easier (speaking from personal experience).

The dates are already present anyway in the commits and license files of the dictionaries so that information won't be lost.

Thanks for your time and effort on this

**Comment by marcoagpinto** [comment]
Yes, it is a good point!

:)

On Friday I am going to update the dictionaries and it will be fixed.

PS-> en_GB will have 1622 new words this month.

Kind regards,
