### ISSUE TITLE
missing word Pentadactyl

### ISSUE THREAD

**Issue by hrzhu** [marcoagpinto/aoo-mozilla-en-dict#25]
The title is self-explanatory. [Source](http://www.oxforddictionaries.com/definition/english/pentadactyl).

**Comment by marcoagpinto** [comment]
I will look at it on Monday... I am kind of away on the weekends.

Thanks!

**Comment by marcoagpinto** [comment]
I have just added:
14256) pentadactyly
14257) pentadactyl
14258) pentadactylic
14259) pentadactylous
14260) pentadactylism
14261) pentadecane
