### ISSUE TITLE
PT show duplicates

### ISSUE THREAD

**Issue by Ding-adong** [marcoagpinto/aoo-mozilla-en-dict#29]
I think there is an error.
When showing duplicate ie. word line 20,000, the word in the dic (notepad++) is actually 20,001. I think the line number 1 isn't taken into account when exporting the duplicate text file and using notepad++ to load up dic and tx files.

**Comment by marcoagpinto** [comment]
There is no error.

The .dic has a "header" with line 1 having to total number of words.

When you open the .dic with PTG, the header is "invisible" so while editing the .dic what appears as the first line word is in fact the second line.

The exporting of the duplicates is meant to be edited with PTG, but you can open the file with Notepad++ but in such a case you will have to calculate +1 or remove the header by hand temporarily.

:-)
