### ISSUE TITLE
Latest Mozilla Thunderbird release missing a lot of words

### ISSUE THREAD

**Issue by superian** [marcoagpinto/aoo-mozilla-en-dict#31]
With the 2.69 version of the Thunderbird addon I'm seeing..

it's 
hosted 
sending 
minutes
updates
longer
things
only
years
quicker
uses
pages
hates
reviews
behaving
thrusting
everyone's
Fortunately
installed
plugin
into
installing
plugins
specifically
banned
people's
sites
hacker
names

etc etc all highlighted as spelling errors.

Words like 'disable, please, better, caught, nineteen' are not highlighted.

**Comment by marcoagpinto** [comment]
Hello!

You need to update TB to V60.5 released on 29-JAN-2019.

The speller was updated to users quicker than TB was triggered to update.

On TB go to: Help -> About
and install 60.5.

Tell me if this solves the issue.

Thank you!

**Comment by superian** [comment]
Ah, I would have expected some sort of 'requires 60.5+' in the Mozilla process for pushing addon updates!

I'm using Ubuntu, and 60.5 has only just arrived in the Debian Sid repositories, so it will be a few days before it trickles down.

I was struck by the way that there's no obvious pattern to the words. Many of them are plurals or -er/-ing, but plenty are not, and the words it does still recognise aren't always simple.

**Comment by jlarkin-oxford** [comment]
Hi, 

I can confirm the same behaviour with Thunderbird 60.4 (Windows 32 bit). Upgrading to 60.5 has solved the issue for me. However, I agree that a flag that 60.5 is needed would be a useful addition. 

All the best, 
James

**Comment by marcoagpinto** [comment]
> 
> 
> Hi,
> 
> I can confirm the same behaviour with Thunderbird 60.4 (Windows 32 bit). Upgrading to 60.5 has solved the issue for me. However, I agree that a flag that 60.5 is needed would be a useful addition.
> 
> All the best,
> James

Hello James,

There is no way I can do that.

The speller .xpi only has a:  manifest.json

And inside it is only one line:
`{"dictionaries": {"en-GB": "dictionaries/en-GB.dic"}, "version": "2.69", "browser_specific_settings": {"gecko": {"id": "marcoagpinto@mail.telepac.pt"}}, "name": "British English Dictionary (Marco Pinto)", "manifest_version": 2}`

The line doesn't allow to specify versions.

What I have done was to write the minimum requirements in the speller page of FF and TB.

**Comment by jlarkin-oxford** [comment]
Thaks for the rapid update. I will leave this for the OP to confirm their fix.

**Comment by marcoagpinto** [comment]
@superian 
Yesterday I turned on my other laptop which has VMs with Ubuntu, and there was an update to Thunderbird.

Has it solved the issue?


@jlarkin-oxford 
Is the issue solved? Can I close this issue?

Is "OP", "Oxford Press"?

:-)

**Comment by jlarkin-oxford** [comment]
Yes, I'm happy to have it closed. OP is Original Poster (i.e. superian in this case), so I was waiting to see if they are also happy for the issue to be closed. Sorry for the slang!

**Comment by superian** [comment]
https://packages.ubuntu.com/search?keywords=thunderbird still shows 60.4 as the latest version in the repositories for all versions of Ubuntu, and that's what I have here. I will close the issue though.

Have you raised the lack of 'requires' with Mozilla? If they're going to break things, like abandoning the XUL interface with Firefox and now this, they should have this.

**Comment by superian** [comment]
https://packages.ubuntu.com/search?keywords=thunderbird still shows 60.4 as the latest version in the repositories for all versions of Ubuntu, and that's what I have here. I will close the issue though.

Have you raised the lack of 'requires' with Mozilla? If they're going to break things, like abandoning the XUL interface with Firefox and now this, they should have this.

**Comment by marcoagpinto** [comment]
> Have you raised the lack of 'requires' with Mozilla? If they're going to break things, like abandoning the XUL interface with Firefox and now this, they should have this.

I know... but the last time I asked for something from Mozilla, they took months to do something about it.
