### ISSUE TITLE
Addition to AFF file

### ISSUE THREAD

**Issue by Ding-adong** [marcoagpinto/aoo-mozilla-en-dict#32]
Check this out will you. Trimming double suffixes by using `=` as presently not in use.

SFX = Y 2
SFX = 0 lessness [^ly] 
SFX = 0 lessnesses [^ly] 

affect/p=hVvNnkDiSG  I added p as it should be there in the first place. No need for affectless (p) and affectlessness & affectlessnesses (=).

What do you think? Let me know and I will look for more savings.

**Comment by marcoagpinto** [comment]
Hey hey!

:-)

I must tell you that the idea is great, the big problem is that Oxford Dictionaries seldom gives examples with lessness and lessnesses.

If I am able to find words with such an ending during February, I will add the rule to the .AFF .

:-)

Thank you, Dingo!

**Comment by Ding-adong** [comment]
lessness is no problem in O.D. as you already have 83 common words covered. Adding es is plural and only matters when someone use plural, so won't affect the spell checker.

**Comment by marcoagpinto** [comment]
Cool!

I will add it then, today or tomorrow.

:-)

**Comment by Ding-adong** [comment]
Not yet... I haven't finish.

**Comment by Ding-adong** [comment]
All done. Spotted an error with missing p account/MBlSGp.

SFX = Y 15
SFX = y ilessness [^aeiou]y 
SFX = y ilessness's [^aeiou]y 
SFX = y ilessnesses [^aeiou]y 
SFX = 0 lessness [aeiou]y 
SFX = 0 lessness's [aeiou]y 
SFX = 0 lessnesses [aeiou]y 
SFX = 0 essness ll
SFX = 0 essness's ll
SFX = 0 essnesses ll
SFX = 0 lessness [^l]l 
SFX = 0 lessness's [^l]l 
SFX = 0 lessnesses [^l]l 
SFX = 0 lessness [^ly] 
SFX = 0 lessness's [^ly] 
SFX = 0 lessnesses [^ly]

**Comment by marcoagpinto** [comment]
@Ding-adong 

Hello!

I have just released PTG build 139.

It now decodes properly more complex rules also using dots.

Force a refresh in the site if the previous page is in cache.

**Comment by marcoagpinto** [comment]
@Ding-adong 

Sorry for taking long, but I have finally inserted the "=" flag into the .AFF, plus:
42967) gas/FC -> moved to outside: "congas" & "degas"
42968) gas's + gases + gassed (merged into gas)
42969) affectless + affectlessness (merged into affect: affect/p=hVvNnkDiSG)

**Comment by Ding-adong** [comment]
Where is the commits? Just to double check.
gaseity; gaseosity gas/MSDGR2Zm5JC and so on.

gaseously; gassier; gassiest are not valid word according to OD.

Will look at adding ous as suffix to the AFF file. Would that be a great addition?

**Comment by marcoagpinto** [comment]
https://en.wiktionary.org/wiki/gaseously

"gassier" and "gassiest" only appear in Premium accounts.

I tried it with my account and it appears in Oxford.

I tried the normal Oxford without the account and there is no mention of them.

**Comment by marcoagpinto** [comment]
Ahhh... no commits as I only added the words from this threat.

I haven't had the change of making all the changes.
