### ISSUE TITLE
Seems to have been broken in Thunderbird 60.4.0

### ISSUE THREAD

**Issue by draxil** [marcoagpinto/aoo-mozilla-en-dict#34]
I'm having a lot of trouble with this dictionary in thunderbird 60.4.0, the current Ubuntu version as far as I'm aware. Suddenly simple things like pluralised words seem to confuse it. 

I assume this is some incompatibility between versions however I have tried removing, adding and updating the dictionary via Thunderbird to no avail.  The US English dictionary "works" in that it doesn't suffer from this problem.

The extension shows as version 2.69 in the extension manager.

**Comment by marcoagpinto** [comment]
Hello!

The dictionary is now a WebExtension and requires TB/FF 60.5.0 or higher:
Software requirements (WebExtension):
Firefox:
 — 60.5+ ESR (29-JAN-2019)
 — 62+
Thunderbird:
 — 60.5+ ESR (29-JAN-2019)
 — 65+ 

A few days ago I was told by a user that Debian or so made a 60.5.1 release.

That will fix the dictionary issues.

Thanks!

**Comment by draxil** [comment]
Thanks! 

I  couldn't get that in my ubuntu, however I added the mozilla ppa and installed via there and all is happy again.

Cheers for your swift help!

Joe
