### ISSUE TITLE
Merriam-Webster

### ISSUE THREAD

**Issue by marcoagpinto** [marcoagpinto/aoo-mozilla-en-dict#35]
@Ding-adong

Hello!

The dictionary above seems to have lots of words not available in Oxford:
https://www.merriam-webster.com/dictionary/arsehole

The problem is that it is an American dictionary, so I need to be cautious about the words I take from it.

Ding-adong, do you think it is a good dictionary and that I should use it?

I will buy a subscription to it still this year, if all goes well.

Thanks!

**Comment by Ding-adong** [comment]
It's ok and 3rd option for me. It tends to cover both USA and UK (sometimes) and useful as Oxford doesn't list all the words.
Why subscription? - it's free.

**Comment by marcoagpinto** [comment]
Thanks!
