### ISSUE TITLE
Errors in FLAGS "N" and others.

### ISSUE THREAD

**Issue by Ding-adong** [marcoagpinto/aoo-mozilla-en-dict#37]
Doing more work today and stumbled across some errors regarding flag `N` #30.
Sorry, bad news, it's still broken. I can not add `ion` to word like advent - advention.

I added a new line SFX N 0 ion t = advention but SFX N 0 ation [^i]t = adventation was created and I don't want it. It need more adjustments. Firstly is there a point in having `N` and `n` when they do almost the same thing and creates duplication of words.

For the 3rd time, have you read https://www.systutorials.com/docs/linux/man/4-hunspell/#index ? or https://github.com/hunspell/hunspell/releases/download/v1.7.0/hunspell5.pdf ?

In it it does explain other options, eg.
SFX P Y 6
SFX P y iness [^aeiou]y 
SFX P 0 ness [aeiou]y 
SFX P 0 ness [^y] 
SFX P y iness's [^aeiou]y 
SFX P 0 ness's [aeiou]y 
SFX P 0 ness's [^y] 

The above is repeated a few time. I did this.
SFX P Y 3
SFX P y iness/MS [^aeiou]y 
SFX P 0 ness/MS [aeiou]y 
SFX P 0 ness/MS [^y] 
giving ness/ness's/nesses in 3 lines.

Having looked into this for over a month, hunspell.dll needs some improvements. Which hunspell file do you use or open office use?

**Comment by Ding-adong** [comment]
Another one.

SFX n Y 28
SFX n 0 tion a 
SFX n e tion ce 
SFX n ke cation ke 
SFX n e ation [iou]te 
SFX n e ion [^iou]te 
SFX n e ation [^ckt]e 
SFX n el ulsion el 
SFX n 0 lation [aiou]l 
SFX n 0 ation [^aeiou]l 
SFX n er ration er 
SFX n 0 ation [^e]r 
SFX n y ation py 
SFX n y ication [^p]y 
SFX n 0 ation [^aelry] 
SFX n 0 tions a 
SFX n e tions ce 
SFX n ke cations ke 
SFX n e ations [iou]te 
SFX n e ions [^iou]te 
SFX n e ations [^ckt]e 
SFX n el ulsions el 
SFX n 0 lations [aiou]l 
SFX n 0 ations [^aeiou]l 
SFX n er rations er 
SFX n 0 ations [^e]r 
SFX n y ations py 
SFX n y ications [^p]y 
SFX n 0 ations [^aelry] 

change to

SFX n Y 14
SFX n 0 tion/S a 
SFX n e tion/S ce 
SFX n ke cation/S ke 
SFX n e ation/S [iou]te 
SFX n e ion/S [^iou]te 
SFX n e ation/S [^ckt]e 
SFX n el ulsion/S el 
SFX n 0 lation/S [aiou]l 
SFX n 0 ation/S [^aeiou]l 
SFX n er ration/S er 
SFX n 0 ation/S [^e]r 
SFX n y ation/S py 
SFX n y ication/S [^p]y 
SFX n 0 ation/S [^aelry] 

saving 14 lines.

**Comment by marcoagpinto** [comment]
@Ding-adong 

I am "gone" for the weekend.

Flag "n" allows to add singular and plural while "N" only adds singular.

This is the way I have been using it.

In the weekend I can't dedicate time to the .aff ... the maximum I can do is add a few words or so.

On Monday I will be back at it.

**Comment by Ding-adong** [comment]
Hope you had a good weekend. Sorted `N`.
SFX N 0 ation [^i]t to SFX N 0 ation [^v].[^i]t

**Comment by marcoagpinto** [comment]
> 
> 
> Doing more work today and stumbled across some errors regarding flag `N` #30.
> Sorry, bad news, it's still broken. I can not add `ion` to word like advent - advention.
> 
> I added a new line SFX N 0 ion t = advention but SFX N 0 ation [^i]t = adventation was created and I don't want it. It need more adjustments. Firstly is there a point in having `N` and `n` when they do almost the same thing and creates duplication of words.
> 
> For the 3rd time, have you read https://www.systutorials.com/docs/linux/man/4-hunspell/#index ? or https://github.com/hunspell/hunspell/releases/download/v1.7.0/hunspell5.pdf ?
> 
> In it it does explain other options, eg.
> SFX P Y 6
> SFX P y iness [^aeiou]y
> SFX P 0 ness [aeiou]y
> SFX P 0 ness [^y]
> SFX P y iness's [^aeiou]y
> SFX P 0 ness's [aeiou]y
> SFX P 0 ness's [^y]
> 
> The above is repeated a few time. I did this.
> SFX P Y 3
> SFX P y iness/MS [^aeiou]y
> SFX P 0 ness/MS [aeiou]y
> SFX P 0 ness/MS [^y]
> giving ness/ness's/nesses in 3 lines.
> 
> Having looked into this for over a month, hunspell.dll needs some improvements. Which hunspell file do you use or open office use?

Hello!

I am not a big fan of twofold (rules that call subrules)

**Comment by Ding-adong** [comment]
Don't do the SFX P. There is a limit in hunspell, 1 prefix and two suffixes. I thought it meant /MS < two suffixes. I had an example of /YP then P /MS making four suffixes and it wouldn't work. Don't do any changes as I have done many fixes in the AFF file already and still inputting the `ous`. Taking longer than expected. Be about 3 more days.

**Comment by marcoagpinto** [comment]
> 
> 
> Don't do the SFX P. There is a limit in hunspell, 1 prefix and two suffixes. I thought it meant /MS < two suffixes. I had an example of /YP then P /MS making four suffixes and it wouldn't work. Don't do any changes as I have done many fixes in the AFF file already and still inputting the `ous`. Taking longer than expected. Be about 3 more days.

@Ding-adong 
I have just fixed PTG.
It now processes well the:
affected/EPY

I noticed that it added "es" to all "'s" in cases like:
aimlessness's
aimlessnesses <- added word
This increased the wordlist in around 1800 words which covers more cases.

Can you confirm if all "ness" have "nasses" as plural (as a native speaker)? This is an important addition to the wordlist.

What is that limit you talked about? Can you unmunch the GB speller in Ubuntu (using the official Hunspell package) with the twofold rule and check in a diff if the only difference are the "nesses"?

If you can't use Ubuntu, tomorrow I will talk to some people on IRC asking them how to do it as I have only done it in 2013 or so and can't remember how.

Thank you for all your help!

**Comment by marcoagpinto** [comment]
@Ding-adong 
This is what I mean by fixing it in PTG minutes ago:
(before:)
![before](https://user-images.githubusercontent.com/5192600/54140861-75583980-441c-11e9-9440-e28455493968.png)

(after:)
![after](https://user-images.githubusercontent.com/5192600/54140878-7db07480-441c-11e9-9075-df6746b62e39.png)

**Comment by Ding-adong** [comment]
All ness plural are es on the end. It actually saves space. So far I've added maybe hundreds of new missing words and saved even more by being efficient. The dic now 300 lines lower than the start and that is with more words. So far so good eh. Remember with plural, just because you haven't seen anyone use it, it doesn't mean it is wrong.

Remember don't change the dic otherwise comparison will be more difficult. I moved prefix letters to the end of the word ie /YPE. Firstly, it is very hard to read and track when the list of words are randomised and not in logical order, easy to read quickly.

A list so far. put he letters in those order and it looks and read better.
Affix order for easy reading, almost alphabetical order, and short to longest words.
WYP
MSDG
Dh
Gk
GJk
Ww1
Qstq uk 89+- usa
YR
7l
36j
ZY
R3
Vvu
RN(or)n
Oo

**Comment by marcoagpinto** [comment]
> In it it does explain other options, eg.
> SFX P Y 6
> SFX P y iness [^aeiou]y
> SFX P 0 ness [aeiou]y
> SFX P 0 ness [^y]
> SFX P y iness's [^aeiou]y
> SFX P 0 ness's [aeiou]y
> SFX P 0 ness's [^y]
> 
> The above is repeated a few time. I did this.
> SFX P Y 3
> SFX P y iness/MS [^aeiou]y
> SFX P 0 ness/MS [aeiou]y
> SFX P 0 ness/MS [^y]
> giving ness/ness's/nesses in 3 lines.

Done and tested with Thunderbird!

**Comment by marcoagpinto** [comment]
> Having looked into this for over a month, hunspell.dll needs some improvements. Which hunspell file do you use or open office use?

I don't use any Hunspell file. I coded the engine myself.

**Comment by Ding-adong** [comment]
`Don't do the SFX P. There is a limit in hunspell, 1 prefix and two suffixes.`
It won't work properly and I have kept the original intact.
Where is your engine then? Is it the same as hunspell or what?

**Comment by marcoagpinto** [comment]
> 
> 
> `Don't do the SFX P. There is a limit in hunspell, 1 prefix and two suffixes.`

Well, it worked okay with Thunderbird, so, it should work also with others?

> It won't work properly and I have kept the original intact.
> Where is your engine then? Is it the same as hunspell or what?

I coded the engine myself based on how Hunspell works (people explained to me how things worked and based on that I coded it myself).

**Comment by marcoagpinto** [comment]
> > `Don't do the SFX P. There is a limit in hunspell, 1 prefix and two suffixes.`
> > It won't work properly and I have kept the original intact.
> 
> Well, it worked okay with Thunderbird, so, it should work also with others?


Damn... better not to risk because some software may still run an old version of Hunspell, so I am going to revert the flag and just add the plural rule to it.

**Comment by Ding-adong** [comment]
You do realise that this dic and aff is being used by other software, not just browsers, but editing subtitles, etc. Others use Hunspell, backward compatible. Why didn't you use hunspell. It's well coded and small filesize? It looks like a lot of hassle creating an engine for no reason.

**Comment by marcoagpinto** [comment]
> 
> 
> You do realise that this dic and aff is being used by other software, not just browsers, but editing subtitles, etc. Others use Hunspell, backward compatible. Why didn't you use hunspell. It's well coded and small filesize? It looks like a lot of hassle creating an engine for no reason.


This is how I work. I code things myself based on the explanation of how they work.

:-)

How could I have coded the PhD project (software) without doing it this way?

Maybe I am silly, but I always get good results.

**Comment by Ding-adong** [comment]
Fair enough. It's your time. Does your engine follow the same rules as hunspell or is there any differences? If so like what?

**Comment by marcoagpinto** [comment]
> 
> 
> Fair enough. It's your time. Does your engine follow the same rules as hunspell or is there any differences? If so like what?


It is supposed to work exactly like Hunspell with the exception that it won't work 100% okay with some language specific rules like the Dutch.

The Dutch speller has Hunspell commands created just for it and without documentation and examples, I can't code them into PTG.

Another reason why I could never use the Hunspell DLL directly is because I don't know how to do it from inside PureBasic.

The RegExp library was built into PureBasic, so there were commands to use it... but there are no Hunspell commands in PureBasic... there was no other choice or way of achieving it... I had to do the hard way...

**Comment by Ding-adong** [comment]
Interesting. some links may help.
https://www.purebasic.fr/english/viewtopic.php?t=43739
https://www.purebasic.fr/english/viewtopic.php?f=12&t=49236&start=0

**Comment by marcoagpinto** [comment]
Last night I improved the "P" flag to do plurals (-nesses):

> SFX P Y 9
> SFX P y iness [^aeiou]y 
> SFX P 0 ness [aeiou]y 
> SFX P 0 ness [^y] 
> SFX P y inesses [^aeiou]y 
> SFX P 0 nesses [aeiou]y 
> SFX P 0 nesses [^y] 
> SFX P y iness's [^aeiou]y 
> SFX P 0 ness's [aeiou]y 
> SFX P 0 ness's [^y]

**Comment by Ding-adong** [comment]
I've told you I'd have already done it, 4 days ago.

**Comment by Ding-adong** [comment]
What is the fundamental differences between R and r?
I understand that sometimes a word ending with a letter mostly have `er`, for example, but sometimes `ier`, thus needing two flags.

**Comment by Ding-adong** [comment]
Can not use `N n` to add `ation` for words ending `er` such as `ponder`. It assumes all `er` are converted to `re`.

**Comment by marcoagpinto** [comment]
I have been improving myself the rules of the .aff as I clean the .dic .

It will go slowly but it is happening.
