### ISSUE TITLE
Plural possessive apostrophes not recognised as correct

### ISSUE THREAD

**Issue by jrawle** [marcoagpinto/aoo-mozilla-en-dict#40]
I use the British English Dictionary in Firefox. I have noticed that when I place an apostrophe after a plural, this is marked as an error. The alternatives offered are the plural or the singular possessive.

For example, in a sentence such as:
"The owners' cars can be parked on the houses' drives."

"owners'" and "houses'" are underlined as mistakes. It offers "owners" or "owner's", etc.

I have been using British dictionaries in Firefox for many years, and not noticed this before. Please can it be corrected?

Many thanks.

**Comment by marcoagpinto** [comment]
Hello!

Thank you for spotting this.

I believe Mozilla must have changed the Hunspell language engine and it is causing this.

I have opened a ticket in Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1569033

I have tried your sentence in Thunderbird, and there it works well, so it is a Firefox issue.

Let us wait to see what Mozilla says about the issue.

Thank you for the report.

**Comment by marcoagpinto** [comment]
Hello!

Can you confirm if the issue is solved?

Thanks!

**Comment by jrawle** [comment]
If appears to be working correctly in Firefox 69. Thanks!

**Comment by marcoagpinto** [comment]
Hey!

Good to know!

Kind regards,
