### ISSUE TITLE
Add 'antisemitism'

### ISSUE THREAD

**Issue by hvdijk** [marcoagpinto/aoo-mozilla-en-dict#44]
In March, 'antisemitic' was added as an alternative for 'anti-Semitic', but 'antisemitism' was not added as an alternative for 'anti-Semitism'. This is listed as a valid spelling on <https://www.lexico.com/definition/anti-semitism> and preferred by <https://www.holocaustremembrance.com/antisemitism/spelling-antisemitism> and others. Can you please add it to the list?

**Comment by marcoagpinto** [comment]
Sure, I will take a look at it tomorrow morning.

**Comment by marcoagpinto** [comment]
Done!

62920) antisemitism (+'s)
