### ISSUE TITLE
Missing words from EN GB

### ISSUE THREAD

**Issue by paulmdavies** [marcoagpinto/aoo-mozilla-en-dict#45]
Marco, thanks so much for your great work on this - your word list is by far the best I can find on the internet.

A couple of words are missing that I've found - I'm making a word game where a user can find arbitrary words in a grid, which are then checked against your list, and I'm finding some omissions as I test:
- [redeal](https://www.wordsense.eu/redeal/) and probably derivatives as well, such as redealt
- [filo](https://www.wordsense.eu/filo/)

**Comment by marcoagpinto** [comment]
Heya,

I just got home and added your words:
64051) redeal (+s +ing +redealt - +'s as it can also be a noun)
64052) filo (+plural +'s)

Thanks!
