### ISSUE TITLE
Firefox displays `pip-label` overlay on videos

### ISSUE THREAD

**Issue by krayon** [marcoagpinto/aoo-mozilla-en-dict#46]
Similar to [this old Reddit post](https://www.reddit.com/r/Fedora/comments/dnvp4b/firefox_showing_banner_with_span_class_at_the_top/) with Firefox 91.0.2 (64 bit) on Linux, a permanent banner overlay appears atop videos:

![screenshot-20211006@050537](https://user-images.githubusercontent.com/103746/136081001-3e6ed57d-86fb-455f-bc92-adefaf3fcf00.png)

Removing "British English Dictionary (Marco Pinto)" seems to resolve this issue.

**Comment by marcoagpinto** [comment]
Heya,

Dictionaries are basically two text files, one with the wordlist and flags (.dic) and the other with the derivation flags (.aff).

All the spellchecking is done by Firefox and Thunderbird using these files.

There is nothing I can do.
