### ISSUE TITLE
Add "Khyber Pahktunkhwa"

### ISSUE THREAD

**Issue by mayhair** [marcoagpinto/aoo-mozilla-en-dict#48]
A province of Pakistan. Listed in the Collins Dictionary:
https://www.collinsdictionary.com/dictionary/english/khyber-pahktunkhwa

**Comment by marcoagpinto** [comment]
Sure, I have just added it:
`84296) Khyber + Pahktunkhwa + Pahktunkhwa's (Collins Dictionary)`

Thanks!
