### ISSUE TITLE
Add proper name “Emmeline”

### ISSUE THREAD

**Issue by wjt** [marcoagpinto/aoo-mozilla-en-dict#50]
It's an uncommon name, but still in active use among English speakers. The [Wikipedia article][w] lists a number of notable Emmelines, of whom [Pankhurst](https://en.wikipedia.org/wiki/Emmeline_Pankhurst) is probably the most well-known.

That article lists various other spellings: Emiline, Emmilene, Emmaline, or Ameline. I can't say I've ever come across these in real life. Émeline is used by French speakers.

[w]: https://en.wikipedia.org/wiki/Emmeline_(given_name)

**Comment by marcoagpinto** [comment]
Ahhhhhh… Thanks, I have added it:
86198) Emmeline + Emmelines + Emmeline's

Kind regards,
