### ISSUE TITLE
Add 'disconcerting'

### ISSUE THREAD

**Issue by MisterSausage** [marcoagpinto/aoo-mozilla-en-dict#51]
For some reason, _disconcerting_ seems to be missing, even though _disconcert_, _disconcertingly_, _disconcerts_ and _disconcerted_ are all present.

Could this be added, please? I believe it would make the entry `disconcert/kSDG`.

Thank you

**Comment by marcoagpinto** [comment]
Heya,

I have just added it:
`86354) disconcerting`

Thanks!
