### ISSUE TITLE
Add proper name “Euan”

### ISSUE THREAD

**Issue by wjt** [marcoagpinto/aoo-mozilla-en-dict#53]
It's a [Scottish male given name](https://en.wikipedia.org/wiki/Euan), related to Owen (and, more distantly, John), in relatively wide use here in the UK.

**Comment by marcoagpinto** [comment]
86631) Euan/M
86632) Heng/M
86633) Macleod/M
86634) Uglow/M
86635) Byers/M
86636) Abercrombie/M

Here is the Euan, let me take care of the other ticket.

**Comment by wjt** [comment]
Thanks – my local checkout at commit 2ec63d5 (which is the latest commit in this repo) did not contain Euan. Do you maintain the lists locally and only push to Git to release? Or is there somewhere else I can look for work-in-progress changes?

**Comment by marcoagpinto** [comment]
Hello!

I used to commit the text with the words as I added them around daily, but I lost that habit when TortoiseSVN had a bug and I had to make the commits with GitHub's official app in the other computer.

They fixed TortoiseSVN, but now I only commit files when there is a release.
