### ISSUE TITLE
Add ‘Czechia’ to GB & ZA

### ISSUE THREAD

**Issue by wjt** [marcoagpinto/aoo-mozilla-en-dict#54]
It's already in AU, CA, and US.

The Czech Republic [made Czechia its official English short name in 2016](https://en.wikipedia.org/wiki/Name_of_the_Czech_Republic#Adoption_of_Czechia)..

**Comment by marcoagpinto** [comment]
Done!

`86692) Czechia + Czechia's (also added to the ZA dictionary)`

**Comment by marcoagpinto** [comment]
Guess what, ZA has the same bug in the rule that existed in GB.

This means that its .aff (affixes file) was the same, or based in the GB one:
![ptg_za_bug_in_rules_20230117](https://user-images.githubusercontent.com/5192600/213023913-1d955176-55b0-4fcd-ac3a-a7eca4cb8bad.png)

Please open a ticket to remember me to fix it.

Thanks!
