### ISSUE TITLE
British English Dictionary contains Americanisms

### ISSUE THREAD

**Issue by RainerBielefeld** [marcoagpinto/aoo-mozilla-en-dict#55]
At LibreOffice _[Bug 153736](https://bugs.documentfoundation.org/show_bug.cgi?id=153736) - British English Dictionary contains Americanisms_ there is a complaint concerning americanisms in en_GB dictionary. And indeed, I found some in this one here.

Can you please have a look?

**Comment by marcoagpinto** [comment]
Heya,

I replied in LibreOffice's Bugzilla.

Thanks!

**Comment by RainerBielefeld** [comment]
Thank you for explication at LibreOffice [Bug 153736](https://bugs.documentfoundation.org/show_bug.cgi?id=153736)
