### ISSUE TITLE
Add MacOS to en-us

### ISSUE THREAD

**Issue by jinbarai** [marcoagpinto/aoo-mozilla-en-dict#56]
Hello, 
It would be nice if we could add `MacOS` as a word to the dictionary. Here's the `English Speller Word Lookup`, that gives the `MacOS` word `***`: http://app.aspell.net/lookup?dict=en_US;words=macOS

Also adding the N-Gram link: https://books.google.com/ngrams/graph?content=macOS&year_start=1800&year_end=2019&corpus=en-US-2019&smoothing=3&case_insensitive=true

**Comment by marcoagpinto** [comment]
Ahhhhh… for en-US you must ask Kevin Atkinson:
https://github.com/en-wl/wordlist

I have the official word used in the en-GB dictionary, and LanguageTool suggests yours as a typo in en-GB:
![macos_20230428](https://user-images.githubusercontent.com/5192600/235202381-b9feced9-9e84-4d5d-9ff4-67c9193faf4c.png)
