### ISSUE TITLE
Add "boustrophedonic"

### ISSUE THREAD

**Issue by Tex2002ans** [marcoagpinto/aoo-mozilla-en-dict#57]
Checked the latest:

- en-GB `V 3.2.0 - 2023-05-01`

It includes:

- boustrophedon
- boustrophedons
- boustrophedon's

but not:

- boustrophedonic

- - -

These dictionaries include the `-ic` adjective form:

- [M-W](https://www.merriam-webster.com/dictionary/boustrophedonic)
- [Collins](https://www.collinsdictionary.com/dictionary/english/boustrophedonic)

**Comment by marcoagpinto** [comment]
Heya,

I have just added:
87799) boustrophedonic + boustrophedonically

Thanks!
