### ISSUE TITLE
Add given name ‘Jemima’

### ISSUE THREAD

**Issue by wjt** [marcoagpinto/aoo-mozilla-en-dict#60]
https://en.wikipedia.org/wiki/Jemima

**Comment by marcoagpinto** [comment]
Heya,

Sorry, I have been terribly busy and didn't notice your e-mail until now.

I have just added the words:
`87850) Jemima + Jemimas + Jemima's`

It is a Proper Name and an elastic-sided boot.

Thanks, and sorry for the delay.
