### ISSUE TITLE
Correct "Khyber Pahktunkhwa" to "Khyber Pakhtunkhwa"

### ISSUE THREAD

**Issue by mayhair** [marcoagpinto/aoo-mozilla-en-dict#62]
After over a year (🤦), I have realised that Collins Dictionary (which I referenced in my previous issue #48) misspells the name of Khyber Pakhtunkhwa, one of Pakistan's provinces. The official name is confirmed by many sources, including Wikipedia, Britannica Online, and the official government.

https://en.wikipedia.org/wiki/Khyber_Pakhtunkhwa
https://www.britannica.com/place/Khyber-Pakhtunkhwa
https://kp.gov.pk/

**Comment by marcoagpinto** [comment]
Heya,

Just in time for tomorrow's release.

😋 

`88150) Corrected "Khyber Pahktunkhwa" to "Khyber Pakhtunkhwa"`
