### ISSUE TITLE
Missing "wharf-" Words

### ISSUE THREAD

**Issue by Tex2002ans** [marcoagpinto/aoo-mozilla-en-dict#67]
wharfage
wharfages

- [M-W](https://www.merriam-webster.com/dictionary/wharfage)
- [Lexico](https://web.archive.org/web/20210830162423/https://www.lexico.com/definition/wharfage)
- [American Heritage](https://www.ahdictionary.com/word/search.html?q=wharfage)
- [Cambridge](https://dictionary.cambridge.org/dictionary/english/wharfage)
- [Collins](https://www.collinsdictionary.com/dictionary/english/wharfage)
- [Dictionary.com](https://www.dictionary.com/browse/wharfage)

wharfman
wharfmen

- [M-W](https://www.merriam-webster.com/dictionary/wharfman)

wharfing

- [M-W](https://www.merriam-webster.com/dictionary/wharfing)
- [American Heritage](https://www.ahdictionary.com/word/search.html?q=wharfing)

wharfinger

- [M-W](https://www.merriam-webster.com/dictionary/wharfinger)
- [Lexico](https://web.archive.org/web/20210830144457/https://www.lexico.com/definition/wharfinger)
- [American Heritage](https://www.ahdictionary.com/word/search.html?q=wharfinger)
- [Cambridge](https://dictionary.cambridge.org/dictionary/english/wharfinger)
- [Collins](https://www.collinsdictionary.com/dictionary/english/wharfinger)
- [Dictionary.com](https://www.dictionary.com/browse/wharfinger)

wharfmaster

- [M-W](https://www.merriam-webster.com/dictionary/wharfmaster)
- [Collins](https://www.collinsdictionary.com/dictionary/english/wharfmaster)
- [Dictionary.com](https://www.dictionary.com/browse/wharfmaster)

- - -

All of these words also exist in the:

- [The Century Dictionary (Volume 8 [1904]), pp. 6885–6886](https://archive.org/details/cu31924091890651/page/6884/mode/2up).

**wharfage**

> 1. Provision of or accommodation at wharves; berthage at a wharf: as, the city had abundant wharfage; to find wharfage for a ship.
> 2. Charge or payment for the use of a wharf; the charges or receipts for accommodation at a wharf or at wharves.

**wharfing**

> 1. A structure in the form of a wharf; materials of which a wharf is constructed; wharves in general.
> 2. In *hydraulic engin.*, a method of facing seawalls by the use of sheet-piling anchored to the bank.

**wharfinger**

> [For *<i>wharfager</i> (with intrusive *n* as in messenger, passenger, porringer, scavenger, etc.), < wharfage + -*er*.]
>
> A person who owns or who has charge of a wharf; one who makes a business of letting accommodation for vessels at his wharf.

**wharfman**

> *n.*; pl. *wharfmen* (-men).
>
> A man employed on or about a wharf; one performing or having charge of work on a wharf.

**wharf-master**

> A wharfinger. [Western U.S.]

- - -

**Note:** There was also this extremely rare word:

- wharfager

which I only saw in the New Century "wharfinger" definition. None of the other easily accessible online dictionaries had it.

Looks like it may have been a tiny bit more "popular" in the 1880s–1920s:

- [Google n-grams: "wharfager"](https://books.google.com/ngrams/graph?content=wharfager&year_start=1800&year_end=2019&corpus=en-2019&smoothing=3)

From a quick skimming in Google Books, I can see it used in a few books/laws from the time period dealing with ports.

**Comment by marcoagpinto** [comment]
Heya,

I have added them:
```
88701) wharfage + wharfages + wharfage's
88702) wharfman + wharfman's + wharfmen + wharfmen's
88703) wharfing + wharfings + wharfing's + wharfinger + ers + er's
88704) wharfmaster + wharfmasters + wharfmaster's
```

Is this “wharfager” to be added?

Is it a noun (+ers +er's)?


Thanks for the words!

**Comment by Tex2002ans** [comment]
> Is this “wharfager” to be added?
> 
> Is it a noun (+ers +er's)?

That one's up to you... depending on how rare you want to go in your word lists. :P

I'm assuming it's a usual noun.

For example, see:

> The owner or occupier of a wharf is styled a "*wharfinger*," properly "wharfager."

from this book, p. 19:

- ["Ports and Terminal Facilities" (1926) by Roy S. MacElwee, PhD](https://www.google.com/books/edition/Ports_and_Terminal_Facilities_by_Roy_S_M/ivZJAAAAMAAJ?hl=en&gbpv=1&dq=%22wharfager%22&pg=PA19&printsec=frontcover)

**Comment by marcoagpinto** [comment]
Done!

Thanks!

`88714) wharfager + wharfagers + wharfager's`
