### ISSUE TITLE
Add support for Pale Moon browser in the Legacy extension

### ISSUE THREAD

**Issue by nicolaasjan** [marcoagpinto/aoo-mozilla-en-dict#75]
Hi,
Your [Legacy extension](https://github.com/marcoagpinto/aoo-mozilla-en-dict/tree/master/Extension%20-%20Firefox%20%2B%20Thunderbird%20%2B%20SeaMonkey%20(GB)%20(Legacy)) will also work on [Pale Moon](http://www.palemoon.org/) with this snippet added to `install.rdf`:
```

    <!-- Pale Moon 28.10 - 33.x.x -->
    <em:targetApplication>
      <Description>
      <em:id>{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}</em:id>
      <em:minVersion>28.10.0</em:minVersion>
      <em:maxVersion>33.*</em:maxVersion>
      </Description>
    </em:targetApplication>
```

**Comment by marcoagpinto** [comment]
Heya,

Thanks!

On 1-MAR, it will be done!

This month I have already released the dictionaries and got too stressed with all the enhancements requested. 😛 😛 😛 😛 

I am drinking cola to get energy.

😋 😋 😋 😋 😋

**Comment by marcoagpinto** [comment]
Done!

On 1-MAR it will go live.

😛😛😛😛😛😛😛😛😛

**Comment by nicolaasjan** [comment]
> Done!
> 
> On 1-MAR it will go live.
> 
> 😛😛😛😛😛😛😛😛😛

Thanks a lot! 👍️

**Comment by Gittyperson** [comment]
Thank you for Pale Moon support! Note it's on v34 now so that "28.10 - 33.x.x" string probably needs updating.

**Comment by marcoagpinto** [comment]
> Thank you for Pale Moon support! Note it's on v34 now so that "28.10 - 33.x.x" string probably needs updating.

Heya,

I have just uploaded it to the folder: “Firefox, Thunderbird, others” folder: 
`british_english_dictionary_marco_pinto-4.0.7-legacy_palemoon34.xpi`

Please test and report if it works.

Thanks!

**Comment by Gittyperson** [comment]
Works just fine. 😊
