### ISSUE TITLE
Recognise archaic second-person and third-person singular forms?

### ISSUE THREAD

**Issue by Crissium** [marcoagpinto/aoo-mozilla-en-dict#77]
Hello! First of all I'd like to express my gratitude for all the time and effort you have invested in this project to bring high-quality morphology dictionaries to everyone.

As someone who is doing a research project involving a significant amount of archaic English, I'd love to suggest a new feature: recognises words like *shouldst*, *hast*, *hath*, *doth*, *saith*, *sayest*, *runneth*, *standeth*, *taketh*, *knowest*, *believest*, etc. (Actually *hast*, *hath*, *doth* these three already work)

I don't know much about the internal workings of Hunspell but it seems to me a trivial addition? If this could be done, I (and other people who work with archaic texts) would be very grateful. Thank you for your consideration!

**Comment by marcoagpinto** [comment]
Heya,

I have only added them because they don't create false positives.

```
89712) shouldst + saith + sayest + runneth + standeth + taketh
              + knowest + believest
Archaic, but doesn't cause FPs
```
